-- 코드를 입력하세요
-- HAVING절은 SUM과 같이 집계함수를 사용했을 때, 걔에 대한 조건만 걸어줄 수 있다.
-- 즉, B.STATUS = 'DONE'는 집계함수와 관련이 없으므로, WHERE절에 넣어준다.

SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3 ASC;
