-- 가격대 별(만 원 단위)로 끊기 위해, PRICE를 10000으로 나눈 후 FLOOR 처리 후 10000을 곱한다.
-- FLOOR 함수는 ROUND와 달리, 버림할 자리수를 정할 수 없다.

SELECT FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY 1 ASC;
