-- COUNT를 하기 위해서는 GROUP BY가 필요하다.
-- GROUP BY에서 FISH_TYPE으로 묶으니 오류가 발생한다. FISH_NAME으로 묶었더니 정상 동작한다.

-- 맞은 풀이

SELECT COUNT(F.FISH_TYPE) AS FISH_COUNT, N.FISH_NAME AS FISH_NAME
FROM FISH_NAME_INFO N
  JOIN FISH_INFO F
  ON N.FISH_TYPE = F.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC;


-- 다른 풀이

SELECT COUNT(FISH_TYPE) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO
    JOIN FISH_NAME_INFO
    USING (FISH_TYPE)
GROUP BY FISH_NAME
ORDER BY 1 DESC;
