-- 코드를 작성해주세요
-- JOIN을 하면, E 테이블 쪽에는 DEPT_NAME_KR 또는 DEPT_NAME_EN가 없기 때문에,
-- DEPT_NAME_KR 또는 DEPT_NAME_EN로 GROUP BY를 시도할 수 없다.

SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT D
    JOIN HR_EMPLOYEES E
    ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY 3 DESC;
