-- 코드를 입력하세요
-- SUM값을 집계하기 위해, GROUP BY를 사용한다.

SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
    JOIN ICECREAM_INFO I
    ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;
