-- 09:00부터 19:59까지라는 조건에 맞게 HAVING절을 설정한다
-- WHERE절에서 오류가 나는 경우, HAVING절을 고려해본다.

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR ASC;
