-- 연도별 최대 값을 구하는 SUBQUERY를 SELECT절에 넣어준다

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       (SELECT MAX(SIZE_OF_COLONY)
       FROM ECOLI_DATA
       WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY AS YEAR_DEV,
       ID
FROM ECOLI_DATA
ORDER BY 1 ASC, 2 ASC;
