-- 코드를 입력하세요
-- 년, 월 별로 출력 : GROUP BY YEAR, MONTH
-- 상품을 구매한 회원 수는 DISTINCT를 사용하여 구할 수 있다. (GROUP BY 사용하지 않음)
-- ROUND에서 SUBQUERY를 사용하는 이유는, JOIN된 애들만 걸러진 테이블이므로, 2021년에 가입했지만, 상품을 구매하지 않은 사람의 수를 확인할 수 없다.

SELECT YEAR(O.SALES_DATE) AS YEAR
     , MONTH(O.SALES_DATE) AS MONTH
     , COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT O.USER_ID)
             / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM USER_INFO U
    INNER JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;
