-- 코드를 입력하세요
-- 두 개의 값을 더하기 위해, 각각의 SUM을 구하고 +를 사용한다.

SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;
