-- 코드를 입력하세요
-- JULY 테이블은 FLAVOR가 중복되어 나타날 수 있다. 이를 계산해주어야 한다.

SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
GROUP BY J.FLAVOR
ORDER BY F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;
