-- 코드를 입력하세요
-- 풀이 1
-- 같지 않음을 표시할 때 != 또는 <>를 사용하면 된다.

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY 1 ASC;

-- 풀이 2
-- NOT LIKE를 사용할 때, OR이 아닌 AND를 사용한다!
-- 밴다이어그램을 그려보면 알기 쉽다.

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE NOT LIKE 'Neutere%' AND I.SEX_UPON_INTAKE NOT LIKE 'Spayed%')
    AND (O.SEX_UPON_OUTCOME LIKE 'Neutere%' OR O.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY 1 ASC;

-- 풀이 3
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND 
    (SEX_UPON_OUTCOME LIKE 'Spayed%' or SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY 1 ASC;
