-- 코드를 입력하세요
-- '상품 코드 별'이므로, GROUP BY를 사용한다
-- GROUP BY를 하지 않으면, 모든 PRICE * SALES_AMOUNT의 합이 하나로 합쳐져서 출력된다.

SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT P, OFFLINE_SALE O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;
