-- 코드를 작성해주세요
-- 업그레이드가 불가능한 아이템은 왼쪽에 있는 ITEM_INFO의 ITEM_ID가 있지만, 오른쪽에 있는 ITEM_TREE의 PARENT_ITEM_ID가 없다.
-- 이를 이용하려면 LEFT OUTER JOIN을 사용해야 한다.
-- LEFT OUTER JOIN시, ITEM_TREE에 있는 NULL값은 조인되지 않는다. ITEM_INFO에 NULL값을 가진 ITEM_ID가 없기 때문

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
    LEFT OUTER JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;
