-- DATE_FORMAT을 통해 출력 형식을 지정한다.
-- (%Y : 1997, %y : 97, %M : March, %m : 03, %D : 3rd, %d : 03)

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY 1 ASC;
