-- FISH_TYPE에서 BASS가 0이 아닐 수 있음 따라서 아래의 쿼리는 틀린 쿼리
-- GROUP BY로 FISH_NAME을 묶으면, 종류 별로 몇 마리 잡았는지 나옴

-- 틀린 쿼리

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE = 0 OR FISH_TYPE = 1;


-- 맞은 쿼리

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I
    JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
WHERE N.FISH_NAME = 'BASS' OR N.FISH_NAME = 'SNAPPER';
